name: workflowx
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.6+6

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2            
  flutter_screenutil: ^5.9.3 
  intl: any
  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  flutter_svg: ^2.1.0
  http: ^1.4.0
  percent_indicator: ^4.2.5
  intl_phone_field: ^3.2.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  pin_code_fields: ^8.0.1
  phone_numbers_parser: ^9.0.3
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  mime: ^2.0.0
  http_parser: ^4.1.2
  hugeicons: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/logo/
    - assets/icons/

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/logo/app_logo.png"
  remove_alpha_ios: true
